### ISSUE TITLE
module installation missing packages

### ISSUE THREAD

**Issue by marco-gallinari** [CleverStack/clever-odm#17]
Installation of clever-odm fails on database migrations, but module seems to be installed correctly.

```
⇒  clever install clever-odm                                                               
Attempting to install clever-odm...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-odm...
  ├── Installing NPM modules for clever-odm...
✔    Successfully installed clever-odm...
  ├── Installing bundledDependencies...
  ├── ⚠ Running grunt tasks for module clever-odm...
Running "readme" task
Installation instructions:
1. In the config file for your desired environment (ie. backend/config/local.json), update the clever-odm object with the details for your database.

2. From your project's `backend` folder, run `NODE_ENV=local grunt db`.
The database tables for your modules should now be installed and seeded with data!

Done, without errors.
Running "prompt:odmConfigPrompt" (prompt) task
[?] What environment is this configuration for? LOCAL
[?] Mongo URI: mongodb://localhost:27017/sample
[?] Enable debugging: Yes

Running "cleverOdmCreateConfig" task

Done, without errors.
Running database migrations...
Error: Command failed: /bin/sh -c NODE_ENV=local grunt db
```

Anyway, clever serve fails on error:

```
Waiting...module.js:338
    throw err;
    ^
Error: Cannot find module 'mongoose-dbref'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/marco/clever/memyne_mvp/backend/modules/clever-odm/module.js:6:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Class.module.exports.Class.extend.loadModule (/home/marco/clever/memyne_mvp/backend/lib/classes/ModuleLoader.js:198:18)
    at class_cb (/home/marco/clever/memyne_mvp/backend/node_modules/uberclass/lib/class.js:94:43)
    at /home/marco/clever/memyne_mvp/backend/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/marco/clever/memyne_mvp/backend/node_modules/async/lib/async.js:46:24)
module.js:338
    throw err;
    ^
Error: Cannot find module 'mongoose-dbref'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/marco/clever/memyne_mvp/backend/modules/clever-odm/module.js:6:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Class.module.exports.Class.extend.loadModule (/home/marco/clever/memyne_mvp/backend/lib/classes/ModuleLoader.js:198:18)
    at class_cb (/home/marco/clever/memyne_mvp/backend/node_modules/uberclass/lib/class.js:94:43)
    at /home/marco/clever/memyne_mvp/backend/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/marco/clever/memyne_mvp/backend/node_modules/async/lib/async.js:46:24)
module.js:338
    throw err;
    ^
Error: Cannot find module 'mongoose-dbref'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/marco/clever/memyne_mvp/backend/modules/clever-odm/module.js:6:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Class.module.exports.Class.extend.loadModule (/home/marco/clever/memyne_mvp/backend/lib/classes/ModuleLoader.js:198:18)
    at class_cb (/home/marco/clever/memyne_mvp/backend/node_modules/uberclass/lib/class.js:94:43)
    at /home/marco/clever/memyne_mvp/backend/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/home/marco/clever/memyne_mvp/backend/node_modules/async/lib/async.js:46:24)
```

and if I look at backend/modules/clever-odm/package.json file, I can see that the listed dipendencies differs from the ones on the git repository:

 ```
{
    "name": "clever-odm",
    "description": "CleverStack ODM (NoSQL) Module",
    "version": "1.0.5",
    "main": "module.js",
    "author": {
        "name": "CleverStack",
        "email": "admin@cleverstack.io",
        "web": "http://cleverstack.io"
    },
    "collaborators": [
        "Richard Gustin <richard.gustin86@gmail.com>"
    ],
    "repository": {
        "type": "git",
        "url": "git://github.com/CleverStack/clever-odm.git"
    },
    "bugs": {
        "url": "https://github.com/CleverStack/clever-odm/issues"
    },
    "keywords": [
        "cleverstack",
        "cleverstack-module",
        "cleverstack-backend",
        "odm",
        "object document mapper",
        "dao",
        "mongoose",
        "mongoosejs",
        "mongo",
        "mongodb"
    ],
    "license": "BSD-2-Clause",
    "dependencies": {
        "mongoose": "~3.8.22",
        "mongoose-deep-populate": "~0.0.7"
    },
    "devDependencies": {
        "grunt": "~0.4.2",
        "grunt-prompt": "~1.1.0"
    }
}
```

**Comment by pilsy** [comment]
This was caused because i had not yet released the latest version of the clever-odm module to NPM, which works with the node-seed 1.2.x - however i have released the latest version tonight (2.0.1)
