### ISSUE TITLE
Aftet scaffoloding a new app, running grunt db in backend folder gives error >> Error: Cannot find module 'utils'

### ISSUE THREAD

**Issue by farooqhameed** [CleverStack/clever-odm#21]
Here are the node and clever versions:-

```
Mac-mini:cleverstack user1$ node -v
v0.12.7
Mac-mini:cleverstack user1$ clever -V
1.2.7
```

Scaffolded a new app:-
```
Mac-mini:cleverstack user1$ clever init hello-world
Preparing for installation...
  └── Creating project installation path...
Installing Backend...
  ├── Installation path is /Users/user1/Workspace/cleverstack/hello-world/backend...
Downloading and extracting node-seed...
  ├── Creating local configuration file config/local.json...
  ├── Installing NPM modules...
  ├── Installing NPM modules...ncies...
  ├── Installing bundled modules...ed successfully!
  ├── Installing bower components...
  └──Installing protractor...ents for cs_messenger...
Error: Command failed: /bin/sh -c npm run-script setup-protractorack/hello-world/frontend...
  ├── Installing bower components for cs_table...
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "setup-protractor"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt webdriver:update'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt webdriver:update
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user1/Workspace/cleverstack/hello-world/frontend/npm-debug.log

Error: Command failed: /bin/sh -c npm run-script setup-protractor

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "setup-protractor"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt webdriver:update'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt webdriver:update
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user1/Workspace/cleverstack/hello-world/frontend/npm-debug.log

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
From previous event:
    at /usr/local/lib/node_modules/cleverstack-cli/bin/clever-init:356:18
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at /usr/local/lib/node_modules/cleverstack-cli/bin/clever-init:353:10
    at /usr/local/lib/node_modules/cleverstack-cli/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:95:15)
Status @ 2.967m |   Installation Progress: [▒▒▒▒▒▒▒▒--]  79 %   ┊   Installing: Frontend   ┊   Step: Installing protractor (this might take awhile)...   ┊   Step Time: 1s   ┊
```
The protractor error does not stop so I kept going and added a new greetings module
```
Mac-mini:cleverstack user1$ cd hello-world/
Mac-mini:hello-world user1$ ls
backend		frontend
Mac-mini:hello-world user1$ clever new greetings
Setting up new module... 
✔  Module has been created successfully within /Users/user1/Workspace/cleverstack/hello-world/backend/modules/greetings
✔  Module has been created successfully within /Users/user1/Workspace/cleverstack/hello-world/frontend/app/modules/greetings
Mac-mini:hello-world user1$ clever install clever-odm
Attempting to install clever-odm...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-odm...
  ├── Installing NPM modules for clever-odm...
✔    Successfully installed clever-odm...
  ├── Installing module peerDependencies...
  ├── ⚠ Running grunt tasks for module clever-odm...
Running "readme" task
Installation instructions:
1. In the config file for your desired environment (ie. backend/config/local.json), update the clever-odm object with the details for your database.

2. From your project's `backend` folder, run `NODE_ENV=local grunt db`.
The database tables for your modules should now be installed and seeded with data!

Done, without errors.
Running "prompt:odmConfigPrompt" (prompt) task
[?] What environment is this configuration for? LOCAL
[?] Mongo URI: mongodb://localhost/nodeseed
[?] Enable debugging: Yes

Running "cleverOdmCreateConfig" task

Done, without errors.
Running database migrations...
✔  Successfully installed.
```
Now i moved to backend folder to run grunt db
```
Mac-mini:hello-world user1$ cd backend/
Mac-mini:backend user1$ grunt db
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'utils'
Warning: Task "db" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by farooqhameed** [comment]
Turns out I had to do this before running grunt db
```
export NODE_PATH=./lib/:./modules/
```

I would suggest just updating the getting started guide for this step.
